services:
  - type: web
    name: jobhunter
    env: docker
    plan: free
    docker:
      dockerfile: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobhunter-db
          property: connectionString
      - key: PYTHONPATH
        value: /app

databases:
  - name: jobhunter-db
    databaseName: jobhunter
    user: jobhunter
    plan: free
