name: Build Android APK

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x ./android/gradlew
      
    - name: Build Release APK
      working-directory: ./android
      run: |
        echo "$KEYSTORE" | base64 --decode > release.jks
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=release.jks \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASS \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASS
      env:
        KEYSTORE: ${{ secrets.KEYSTORE }}
        KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASS: ${{ secrets.KEY_PASS }}
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: jobhunter-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 30
